# Generated by Django 3.2.6 on 2021-08-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ingredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ingrediente1', models.CharField(max_length=50)),
                ('ingrediente2', models.CharField(max_length=50)),
                ('ingrediente3', models.CharField(max_length=50)),
                ('ingrediente4', models.CharField(max_length=50)),
                ('ingrediente5', models.CharField(max_length=50)),
                ('receta', models.CharField(max_length=1500)),
            ],
        ),
    ]
